install:
- choco install gitversion.portable -pre -y
assembly_info:
  patch: false
before_build:
- cmd: nuget restore src/Augurk.CommandLine.sln
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
build:
  verbosity: minimal
after_build:
  - cmd: ECHO nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack <Project>\<NuSpec>.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "<NuSpec>.%GitVersion_NuGetVersion%.nupkg"