# Builds the Augurk CLI 

jobs:
- template: ci/build-job.yml
  parameters:
    vmImage: VS2017-Win2016
    runtimeIdentifier: win-x64
    jobName: Windows

- template: ci/build-job.yml
  parameters:
    vmImage: macOS-10.15
    runtimeIdentifier: osx-x64
    jobName: macOS

- template: ci/build-job.yml
  parameters:
    vmImage: ubuntu-16.04
    runtimeIdentifier: linux-x64
    jobName: Linux

- job: NuGetPackages
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
    - script: dotnet --info
      displayName: 'dotnet --info'

    - task: GitVersion@5
      displayName: 'Determine version'
      inputs:
        updateAssemblyInfo: true

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: pack
        projects: 'src/Augurk.CommandLine/Augurk.CommandLine.csproj'
        versioningScheme: byEnvVar
        versionEnvVar: GitVersion.FullSemVer
        configuration: $(buildConfiguration)
        verbosityPack: Normal
        buildProperties: 'Version=$(GitVersion.MajorMinorPatch);InformationalVersion=$(GitVersion.InformationalVersion)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish NuGet package'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: NuGetPackages
        publishLocation: Container